### ISSUE TITLE
Retaining stack across activity restoration

### ISSUE THREAD

**Issue by TomMannson** [JohannBlake/adoptme#3]
Hi, You have idea how to retain stack info. I think the reason is that NavigationInfo can't be placed in Bundle.
Bundle class is Android System method to retain data across such system events.

Do you have a plan to improve it

Case to reproduce:
Add Camera Permision to your example Sourcecode
Open Your App
Navigate so some Deeper place in App (create such navigation stack)
Go to Your App Settings
Disable some permissions
Return to Your App
Actual Result:
Your App will list info about Stack
Expected Result
Application will restore stack in place when It was before action

In real Life
Same scenario sometimes it happens when You are reading some News details (In Your favorite news App) ;) 
Some one call Your Phone
After some time System will snap Your process (How long? It depends on Your RAM and memory management policy) 
After call You want to continue reading where You leave. But You will lose Your stack

**Comment by DrifterAtSea** [comment]
Sorry for the late response. I was busy implementing a complete rewrite that is posted under a new repo that should be released in a few days. The new framework is called Jetmagic and includes more important support for responsive layouts in a way that is similar to how the older view system handles xml layouts by selecting the correct layout based on the device configuration and the qualifiers that you specify on layout folders. But instead of xml and folders, the new framework handles composables and qualifiers are properties. The new framework combines a rewrite of the navigation framework with the support for responsive layouts. I needed to make major modifications to the navigation framework to support that. Not even Google has a solution, so I'm sure the one I've come up with will be something developers will really want.

The one part of your post that wasn't clear when you wrote:

>Your App will list info about Stack

If I understand you, you want the stack to remain "persistant" even when the app (or device) restarts. Is that what you want? If so, that is definitely possible. I'll have to give it some more thought.

**Comment by TomMannson** [comment]
Sorry for typo
To clarify everything I meant
> Your App will **lost** info about Stack.

In Android We have concepts of memory management.
If We switch between apps OS will after time "pause" the application. Pause is not equal to Reset of application.
After pause system will restore some necessary info packed into Bundle objects
ex: If We have multiple Activities the last visible one will be restored in first place.
In my opinion retain navigation stack across device restart is over kill but restoring after process (not Activity) pause -> resume scenario is crucial for good user experience

> I was busy implementing a complete rewrite that is posted under a new repo that should be released in a few days

Nice. It will support dynamic navigation and deeplinks as well?

To be honest I'm not a big fan of NavigationComponent and Google Compose Navigation as well 😄
Good to hear that someone is working on some better and more flexible solution

**Comment by DrifterAtSea** [comment]
The updated framework (Jetmagic) I created does maintain the state of all screens as long as the app is not killed. So even if you switch to a different app and then back, when the screen is restored, any data that was passed into the screen is still available (it never got destroyed) because it's part of the viewmodel, which is managed by the ComposableResourceManager.

Not sure what you mean by "dynamic navigation". Can you give an example?

I will be adding support for deeplinks although it's on my TODO list.

What I think you will like about Jetmagic is that a screen is made up of Composable Instances - which are instances of a class used to maintain the state of composables. These instances can be passed around the Jetmagic framework and used in ways that you can't using Google's approach.

I am putting the finishing touches on the documentation right now and still need to write the ProAndroidDev article, so it will be a few days till the framework is officially released.

**Comment by TomMannson** [comment]
> The updated framework (Jetmagic) I created does maintain the state of all screens as long as the app is not killed.

So You are holding stack in VM with SavedState to persist it when process is suspended by OS?
Great, I will take a look at JetMagic for sure.

> Not sure what you mean by "dynamic navigation". Can you give an example?

I mean navigation to dynamic feature "destination/screen" downloaded from PlayStore as dynamic feature module

**Comment by DrifterAtSea** [comment]
The navigation stack in Jetmagic doesn't use SaveState to persist the viewmodels. If the app is killed, the navigation manager is terminated along with the viewmodels. However, if the app's activity is destroyed, the navigation manager still lives on as long you launch it from a class that inherits from Application. The navigation manager is a singleton. So even if you relaunch the app, the stack will be restored and the app will continue from the screen that was last displayed. This can be seen in Jetmagic's demo app. There's a screen with a button that you can click on that terminates the activity (Acitivity.finish). If you then launch the app again, it restarts on the screen from where it left off.

I haven't given any thought about how to handle navigation for feature modules. To be honest, I haven't used feature modules before as all the apps I've worked on pretty well contained all the features. But I'll look into it.

**Comment by TomMannson** [comment]
Hi, thanks to quick reply

> The navigation manager is a singleton. So even if you relaunch the app, the stack will be restored and the app will continue from the screen that was last displayed.

I'm looking for solution of even worst case then Activity Destruction
Sadly Singletons can't survive the process death but Bundles does.
So there is a case that System will kill Your process but Bundles will be persisted. 
In other words not only Activity will by destroyed but Application also
Thanks to the Bundle/SavedState Objects You could still restore Your Compose stack even after process death

Details of the case are detailed here 
https://medium.com/swlh/android-process-death-66f56029e405#5ee9

> I haven't given any thought about how to handle navigation for feature modules. To be honest, I haven't used feature modules before as all the apps I've worked on pretty well contained all the features. But I'll look into it.

Nice to hear that. I'm waiting for some news 😄

**Comment by DrifterAtSea** [comment]
I'm not sure I see any advantage of restoring the state of anything when the Application is destroyed. If you restore the same state but the thing that caused your app to be destroyed is still present or happens again, that would be frustrating to users. Better off to start with a clean state when the app restarts.

I may have to ditch the singleton anyways due to the way I'm implementing deep linking. If users find that they must be able to restore the state after the app is destroyed, it is still possible to implement since the state of all the screens is stored in a class that can be serialized to disk and later on restored.

**Comment by TomMannson** [comment]
> I'm not sure I see any advantage of restoring the state of anything when the Application is destroyed. If you restore the same state but the thing that caused your app to be destroyed is still present or happens again, that would be frustrating to users. Better off to start with a clean state when the app restarts.

It depends:
If We have broken or incomplete state than You are right that can be frustrating to user. (But that also means We have a bug somewhere in our logic)

Otherwise If We have for example some complex multi step form partially filled on nested screen and in meantime We get a phone call after back to the app We have a chance that content of form will be losed. It can be also frustrating to users.

> I may have to ditch the singleton anyways due to the way I'm implementing deep linking.

Yup, Singleton can be real pain if We will try to test it in isolation or when we will try to use interactive mode in AS (when Google will make it work 😄 )
Second reason is that maybe some time You will want to implement nested navigator and create navigation in some subsection of Your app. 
We had such problem in one app. This app has written in Flutter but JetpackCompose isn't so different.
Maybe some **rememberSavableX** syntax will be a good point.

> If users find that they must be able to restore the state after the app is destroyed, it is still possible to implement since the state of all the screens is stored in a class that can be serialized to disk and later on restored.

I think, that can be good start.
Difficulties in such approach will be to synchronizing stackstate and disk. In Multi threading code there is always a chance for mistakes.
Have you thought about @Parcelize it will generate necessary logic in Parcelable for free. 
Downside is that no every Object can be saved as parcelable.

**Comment by DrifterAtSea** [comment]
Having an activity destroyed when switching between apps is definitely a pain. That's where Jetmagic comes in to save the day. I modifed the code so that it is not a singleton by default, although I strongly recommend using it that way. If you choose to not use the singleton, you'll have to manage the creation of the two main components yourself, either from within your activity or elsewhere. I decided to leave this for developers to figure out because every developer will end up rolling their own solution. But you will have to implement state management if the activity gets destroyed in order to return to the last screen. With the singleton approach, this isn't an issue. Still, I don't want to force any developer to use one approach over another.

> Have you thought about @Parcelize it will generate necessary logic in Parcelable for free.

I haven't really given any thought about serialization at the moment as it's a low priority topic. But if I did I wouldn't use @Parcelize. I would stick to standard JSON serialization annotations and probably would go with Kotlin's flavor.

Jetmagic has been completed. Adding the support for deep linking took much longer than I expected. But it offers some pretty powerful features like launching multiple screens in succession or just the target screen. It also supports handling multiple URIs, redirects on unknown URIs, and a few more features.

Still writing the documentation at this stage and hope it will be finished by the weekend.

**Comment by TomMannson** [comment]
> I decided to leave this for developers to figure out because every developer will end up rolling their own solution.

So, I can implement my own save/restore method? 
Nice

> I would stick to standard JSON serialisation annotations and probably would go with Kotlin's flavor.

If You will ever increase priority of topic I would recommend to not use JSON serialisation method. 
It is designed rather for human readable data transfer format and not for performance.
In some Java (Android) versions it is still faster then Java Serialisation (Serialisable) but using it on UI Thread will result with laggy UI and smoothness of animation will be questionable

> Jetmagic has been completed.

I will definitely try Your solution

BTW, Thanks for support 😄
I think We can close this issue
